linux_task:
  env:
    BUILD_TYPE: "Release"
    QT_VERSION: "5.15.2"
    QT_ARCH: "gcc_64"
  container:
    image: ubuntu:18.04
    cpu: 8
  install_dependencies_script:
    - apt update
    - apt install build-essential python3 python3-pip cmake -y
    - python3 -m pip install aqtinstall
  install_qt_script:
    - python3 -m aqt install-qt linux desktop "$QT_VERSION" "$QT_ARCH" -O "$HOME/Qt"
    - export Qt5_DIR="$HOME/Qt/$QT_VERSION"
  build_script:
    - cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr -DUSE_TESTS=ON
    - cmake --build . --config $BUILD_TYPE
  test_script:
    - "$CIRRUS_WORKING_DIR/spotify-qt/lib/test/spotify-qt-lib-test"
  install_script:
    - make DESTDIR="$CIRRUS_WORKING_DIR/dist" install
  package_script:
    - curl -L https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -o $CIRRUS_WORKING_DIR/linuxdeployqt
    - chmod +x $CIRRUS_WORKING_DIR/linuxdeployqt
  upload_artifacts:
    path: "spotify-qt/*"