linux_task:
  env:
    # Build configuration
    BUILD_TYPE: "Release"
    QT_VERSION: "5.15.2"
    QT_ARCH: "gcc_64"
    # Qt
    Qt5_DIR: "$HOME/Qt/$QT_VERSION/$QT_ARCH"
    QT_PLUGIN_PATH: "Qt5_DIR/plugins"
    # System
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$Qt5_DIR/lib"
    PKG_CONFIG_PATH: "$PKG_CONFIG_PATH:$Qt5_DIR/lib/pkgconfig"
    PATH: "$PATH:$Qt5_DIR/bin"
  container:
    image: ubuntu:18.04
    cpu: 8
  install_dependencies_script:
    - apt update
    - apt install build-essential python3 python3-pip cmake -y
    - apt install libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev libxcb-util1 libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb1 -y
    - python3 -m pip install aqtinstall
  install_qt_script:
    - python3 -m aqt install-qt linux desktop "$QT_VERSION" "$QT_ARCH" -O "$HOME/Qt"
  build_script:
    - cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr -DUSE_TESTS=ON
    - make -j8
  test_script:
    - "$CIRRUS_WORKING_DIR/spotify-qt/lib/test/spotify-qt-lib-test"
  install_script:
    - make DESTDIR="$CIRRUS_WORKING_DIR/dist" install
  package_script:
    - curl -L https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -o $CIRRUS_WORKING_DIR/linuxdeployqt
    - chmod +x $CIRRUS_WORKING_DIR/linuxdeployqt
  artifacts:
    path: "spotify-qt/*"