name: Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Generate docs
      - name: Slate Documentation builder
        uses: Decathlon/slate-builder-action@v1.0.0
