name: Snapcraft Xenial

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: snapcraft/xenial-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: snapcraft-docker
