name: MSYS2

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            cmake
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-qt5-base
            mingw-w64-x86_64-qt5-svg

      - name: Configure CMake
        run: cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_TESTS=ON

      - name: Build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        run: ./lib/test/spotify-qt-lib-test.exe

      - name: Package
        run: |
          curl https://raw.githubusercontent.com/mxe/mxe/master/tools/copydlldeps.sh -o copydlldeps.sh
          ./copydlldeps.sh --infile ./spotify-qt.exe \
            --destdir ./spotify-qt/ \
            --recursivesrcdir /mingw64/bin/ \
            --enforcedir /mingw64/share/qt5/plugins/generic/ \
            --enforcedir /mingw64/share/qt5/plugins/iconengines/ \
            --enforcedir /mingw64/share/qt5/plugins/imageformats/ \
            --enforcedir /mingw64/share/qt5/plugins/platforms/ \
            --enforcedir /mingw64/share/qt5/plugins/styles/ \
            --enforcedir /mingw64/bin/libcrypto-1_1-x64.dll \
            --enforcedir /mingw64/bin/libjpeg-8.dll \
            --enforcedir /mingw64/bin/libssl-1_1-x64.dll \
            --enforcedir /mingw64/bin/Qt5Svg.dll \
            --copy
          cp ./spotify-qt.exe ./spotify-qt/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spotify-qt
          path: ./spotify-qt/
