name: MSYS2

on: [push, pull_request]

env:
  BUILD_TYPE: Releasse

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            cmake
            mingw-w64-i686-cmake
            mingw-w64-i686-qt5

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_TESTS=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE
