name: MSYS2

on: [push, pull_request]

env:
  BUILD_TYPE: Releasse

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            cmake
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-qt6-base
            mingw-w64-x86_64-qt6-svg

      - name: Configure CMake
        run: cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_QT6=ON -DUSE_TESTS=ON

      - name: Build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        run: ./lib/test/spotify-qt-lib-test.exe

      - name: Package
        run: |
          curl https://raw.githubusercontent.com/mxe/mxe/master/tools/copydlldeps.sh -o copydlldeps.sh
          ./copydlldeps.sh --infile ./spotify-qt.exe \
            --destdir ./spotify-qt/ \
            --recursivesrcdir /mingw64/bin/ \
            --enforcedir /mingw64/share/qt6/plugins/generic/ \
            --enforcedir /mingw64/share/qt6/plugins/iconengines/ \
            --enforcedir /mingw64/share/qt6/plugins/imageformats/ \
            --enforcedir /mingw64/share/qt6/plugins/platforms/ \
            --enforcedir /mingw64/share/qt6/plugins/styles/ \
            --copy
          cp ./spotify-qt.exe ./spotify-qt/
          mkdir ./spotify-qt/bin/
          cp /mingw64/bin/*.dll ./spotify-qt/bin/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spotify-qt
          path: ./spotify-qt/
