name: MSYS2

on: [push, pull_request]

env:
  BUILD_TYPE: Releasse

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            cmake
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-qt6-base
            mingw-w64-x86_64-qt6-svg

      - name: Configure CMake
        run: cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_QT6=ON -DUSE_TESTS=ON

      - name: Build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        run: ./lib/test/spotify-qt-lib-test.exe

      - name: Package
        run: |
          mkdir spotify-qt
          cp /mingw64/bin/Qt6*.dll ./spotify-qt/
          cp ./spotify-qt.exe ./spotify-qt/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spotify-qt
          path: ./spotify-qt/
